title: Abhi Patel
subtitle:
description: >- # this means to ignore newlines until "baseurl:"


url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Contact Me
      url : /contact
    - text: Notepad
      url: /notepad

collections:
    notepad:
      output: true

author_logo: profile.png
author: Abhi Patel
author_bio: Mechatronics Engineering Student
author_email: "abhi.patel@ontariotechu.net"
author_location: Canada
author_website_url: "abhipatel.netlify.app"
typewrite-text: Welcome to my site

author_work_experiences:
            - company_name: CAROBOT Learning And Research Organization
              company_logo: carobot.png
              company_url: https://www.carobot.org/
              designation: Hardware Developer
              description: >-
                Designed robot cars for lesson kits.
                Created the logistics, lesson plans and software for summer camp classes
              visibility: true

            - company_name: Telus
              company_logo: telus.jpg
              company_url: https://www.telus.com/en/
              designation: Data Engineering Co-op
              description: Worked on various Telus Products for the Systems for Enterprise Analytics
              visibility: true

author_education_details:
              - college_logo: ontariotechu.png
                college_name: Ontario Tech University
                college_url: https://ontariotechu.ca/
                college_degree: Mechatronics Engineering
                description: Bachelor of Engineering
                visibility: true

author_project_details:
              - project_thumbnail:
                project_title: Meme Vault
                project_description: An application that stores and retrieves memes by indexing them based on user provided descriptions and optical character recognition. 
                project_url: https://github.com/B33Boy/Meme_Vault_Prototype
                visibility: true

              - project_thumbnail:
                project_title: Data-Driven Algorithms Collection
                project_description: A collection of algorithms written from scratch. Includes matrix factorizations, linear and logistic regression, k-means clustering, PCA, Eigenface,  
                project_url: https://github.com/B33Boy/Data-Driven-Algorithms-Collection
                visibility: true

              - project_thumbnail:
                project_title: Invisibility Cloak
                project_description: Colour segmentation based project where the target object becomes transparent.
                project_url: https://github.com/B33Boy/Invisibility_Cloak
                visibility: true

              - project_thumbnail:
                project_title: Pothole Pal
                project_description: Pothole Pal is a proof of concept (POC) demonstrated by an ultrasonic sensor on an Arduino powered car to simulate the ability for a car or autonomous vehicle to drive over a surface and detect potholes in the real world.
                project_url: https://devpost.com/software/potholepal
                visibility: true


              - project_thumbnail:
                project_title: Vocally
                project_description: A tool to improve one's diction by analyzing statistics of filler words.
                project_url: https://devpost.com/software/vocally
                visibility: true

              - project_thumbnail:
                project_title: Self Driving RC Car
                project_description: An attempt at recreating Hamuchiwa's AutoRCCar project. Implemented the neural network in Keras as well as code for data augmentation.
                project_url: https://github.com/B33Boy/Self-Driving-RC-Car
                visibility: true

                

resume: Abhi_Resume_14_June_2020.pdf

# social links
github_username:  b33boy
linkedin_username: abhi-patel-0
medium_username: abhip
devpost_username: abhip202

# wakatime username (coding activity)
wakatime_username: b33boy

# formspree (contact form)
formspree_email: xeqrkrzo

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: K78Z7CV8JS
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: e3393b3def9aa435cc746f1fc15030f5

# pagination of posts
paginate: 8
per_page: 8
paginate_path: "/blog/page/:num/"

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
